language: go

go:
  - 1.12.x

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/konsorten/go-windows-terminal-sequences

script:
  - echo "Starting build"
  - gox -os="linux darwin windows" -arch="amd64" -output="attunity_exporter.." -verbose ./...

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
  - attunity_exporter.windows.amd64.exe
  - attunity_exporter.linux.amd64

on:
  tags: true
