language: go

go:
  - 1.12.x

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/konsorten/go-windows-terminal-sequences

script:
  - echo "Starting build"
  - gox -os="linux darwin windows" -arch="amd64" -verbose ./...
  - ls .

deploy:
  provider: releases
  cleanup: true
  api_key: $GITHUB_TOKEN
  file:
  - attunity_exporter_windows_amd64.exe
  - attunity_exporter_linux_amd64

  on:
    tags: true
